pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
    
#- task: SonarCloudPrepare@1
#  inputs:
#   SonarCloud: 'Sonar Cloud'
#    organization: 'devops-fundamentos-v4-1'
#    projectKey: 'DevOps-Fundamentos-v4-1_springpet-clinic'
#    projectName: 'springpet-clinic'
#    scannerMode: 'Other'
#- task: Gradle@3
#  inputs:
#        gradleWrapperFile: 'gradlew'
#        tasks: 'sonarqube'
#        publishJUnitResults: false
#        javaHomeOption: 'JDKVersion'
#        sonarQubeRunAnalysis: true
#        sqGradlePluginVersionChoice: 'specify'
#        sonarQubeGradlePluginVersion: '3.5.0.2730'
#        spotBugsAnalysis: false